import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { assessSnapshot } from "./drift.js";
import { loadDvnMeta, resolveDvn } from "./lz-config.js";
import { getSnapshot, latestVerdict } from "./snapshot-store.js";
import type { WatchedOft } from "../types.js";

const DEEPSEEK_KEY = process.env.DEEPSEEK_API_KEY;
const SEPOLIA = "https://sepolia.mantlescan.xyz";

const REFERENCE = (() => {
  try {
    const dir = dirname(fileURLToPath(import.meta.url));
    return readFileSync(join(dir, "oft-security-reference.md"), "utf8");
  } catch {
    return "";
  }
})();

// ── LLM full report writer ────────────────────────────────────────────────────

const REPORT_SYSTEM = (REFERENCE
  ? `${REFERENCE}\n\n---\n`
  : "") +
`You are the OFT Sentinel report engine. You will be given structured on-chain security facts for a LayerZero OFT. Write a complete markdown security report.

Rules:
- Use ONLY the facts provided. Never invent DVN names, addresses, counts, or scores.
- Output plain markdown. Do not wrap in a code block.
- Start with: # OFT Sentinel — {ticker} Security Report
- Then a metadata line: **{address}** · Mantle · generated {generated} · Score {score}/100 · {riskLevel}
- Then these sections in order:

## Summary
2-4 sentences. State the overall risk level, what the main findings are, and the protocol's cross-chain footprint (number of active corridors). Be direct.

## Findings
First, a markdown table with columns: | Severity | Check | Detail |
Then, for each CRITICAL or HIGH finding, write a short paragraph (2-3 sentences) explaining what it means specifically for this OFT and why it matters. Skip MEDIUM/LOW/PASS findings in prose — the table covers them.

## DVN Configuration
First, a markdown table with columns: | Corridor | Required DVNs | Confirmations | Send library |
Then, a paragraph interpreting what this configuration means in practice: how many independent verifiers are protecting each corridor, whether the DVN set is diverse, and whether the library setup introduces any upgrade risk.

## Attack Scenario
Write a concrete, specific scenario: given the actual findings and DVN config above, describe the realistic attack path an adversary would take if they exploited the most critical weakness. Name the specific DVN or library involved. Be concise (3-5 sentences). If the configuration is healthy (score ≥ 85), explain why the most obvious attack vectors are closed.

## Trust Assumptions
3-5 bullet points. Each must name a specific DVN or contract from the facts. Do not write generic statements.

## Recommendations
2-5 bullet points, ordered by priority (highest impact first). Each must be a concrete action the protocol team can take, referencing the specific finding it addresses.

## On-chain Record
One line: the attestation tx hash and link if provided, or a statement that no drift has been attested yet.

---
*Generated by OFT Sentinel — deterministic on-chain reads, AI-written report. Not financial advice.*`;

/** Call DeepSeek to write the full report markdown. Returns null on any failure. */
async function writeReport(facts: unknown): Promise<string | null> {
  if (!DEEPSEEK_KEY) return null;
  try {
    const res = await fetch("https://api.deepseek.com/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${DEEPSEEK_KEY}` },
      body: JSON.stringify({
        model: "deepseek-chat",
        temperature: 0.2,
        messages: [
          { role: "system", content: REPORT_SYSTEM },
          {
            role: "user",
            content: "Facts:\n```json\n" + JSON.stringify(facts, null, 2) + "\n```\n\nWrite the full report now.",
          },
        ],
      }),
    });
    if (!res.ok) return null;
    const j = (await res.json()) as any;
    return (j.choices?.[0]?.message?.content as string | undefined) ?? null;
  } catch {
    return null;
  }
}

const cache = new Map<string, { at: number; markdown: string }>();

/** Generate (or return cached) a full AI-written markdown audit report for one watched OFT. */
export async function generateReport(w: WatchedOft): Promise<string | null> {
  const snap = getSnapshot(w.address, w.chainId);
  if (!snap) return null; // not polled yet

  const cacheKey = `${w.address.toLowerCase()}:${snap.capturedAt}`;
  const hit = cache.get(cacheKey);
  if (hit) return hit.markdown;

  const dvnMeta = await loadDvnMeta();
  const srcChainKey = "mantle";
  const { findings, score, riskLevel } = await assessSnapshot(snap, w.ticker);
  const verdict = latestVerdict(w.address, w.chainId);
  const generated = new Date().toISOString().slice(0, 16).replace("T", " ") + " UTC";

  const facts = {
    ticker: w.ticker,
    address: w.address,
    chain: "Mantle",
    generated,
    score,
    riskLevel,
    owner: snap.owner ?? null,
    ownerIsContract: snap.ownerIsContract,
    proxyAdmin: snap.proxyAdmin ?? null,
    proxyAdminIsMultisig: snap.proxyAdminIsMultisig,
    findings: findings.map((f) => ({ severity: f.severity, check: f.check, detail: f.detail })),
    corridors: snap.routes
      .filter((r) => r.isActive && r.uln)
      .map((r) => ({
        corridor: r.chainName,
        requiredDVNCount: r.uln!.requiredDVNCount,
        requiredDVNs: r.uln!.requiredDVNs.map((a) => resolveDvn(a, srcChainKey, dvnMeta)),
        optionalDVNs: r.uln!.optionalDVNs.map((a) => resolveDvn(a, srcChainKey, dvnMeta)),
        optionalThreshold: r.uln!.optionalDVNThreshold,
        confirmations: r.uln!.confirmations,
        sendLibPinned: !r.sendLibIsDefault,
      })),
    attestation: verdict?.attestTxHash
      ? { txHash: verdict.attestTxHash, url: `${SEPOLIA}/tx/${verdict.attestTxHash}` }
      : null,
  };

  const md = await writeReport(facts);
  if (!md) return null;

  cache.set(cacheKey, { at: Date.now(), markdown: md });
  return md;
}
